{% set version = "0.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-narray
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/narray_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/narray/narray_{{ version }}.tar.gz
  sha256: 9d69a65d9d1c0bffe696b37df0d532b096bb91447c440baa41f62d0e8196a12e

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-progress
    - r-stringr
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-progress
    - r-stringr

test:
  commands:
    - $R -e "library('narray')"           # [not win]
    - "\"%R%\" -e \"library('narray')\""  # [win]

about:
  home: https://github.com/mschubert/narray
  license: Apache-2.0
  summary: Stacking arrays according to dimension names, subset-aware splitting and mapping of functions, intersecting along arbitrary dimensions, converting to and from data.frames, and many other helper functions.
  license_family: APACHE
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut
