{% set version = "0.4.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-narray
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/narray_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/narray/narray_{{ version }}.tar.gz
  sha256: e94f2b5f496c1d90f86d0fbbef0e5a0b9a01be49306597cae965c239b6b1def7

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-progress
    - r-stringr
  run:
    - r-base
    - r-progress
    - r-stringr

test:
  commands:
    - $R -e "library('narray')"           # [not win]
    - "\"%R%\" -e \"library('narray')\""  # [win]

about:
  home: https://github.com/mschubert/narray
  license: Apache-2.0
  summary: Stacking arrays according to dimension names, subset-aware splitting and mapping of functions, intersecting along arbitrary dimensions, converting to and from data.frames, and many other helper functions.
  license_family: APACHE
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut
