{% set version = '0.4.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-narray
  version: {{ version|replace("-", "_") }}

source:
  fn: narray_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/narray_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/narray/narray_{{ version }}.tar.gz
  sha256: 3e38bcb23037b4287a82f7a14de99d315b01ff7808ef3a0baac13f31a106c526

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-progress
    - r-stringr
  run:
    - r-base
    - r-progress
    - r-stringr

test:
  commands:
    - $R -e "library('narray')"           # [not win]
    - "\"%R%\" -e \"library('narray')\""  # [win]

about:
  home: https://github.com/mschubert/narray
  license: Apache 2.0
  summary: Stacking arrays according to dimension names, subset-aware splitting and mapping of
    functions, intersecting along arbitrary dimensions, converting to and from data.frames,
    and many other helper functions.
  license_family: APACHE
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
