appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: kqDnw4/nqf1ahx+aiY0hSUzTB9+G0jCOtoIaWFAS8HLBhsVQuKxKEKdQPNxvphkFHEf9tEwE5W4KnD+tmCTuL9VjMsYDNYuyOd3/YzF24UoXZkCp1nfv0QMdYb2RTaWX07W7ZKxMheGi9Fx/I7FPAcIPMFw9KrtuNvfrmBt7I/lw6if+UGCIrS3n3NZITPg51EIfRKfx6S/LCb/MOouhMxr7DahSTSlFUL2oML45Qid+P5q/RYM8UCZcy3whO2CAhdVh4bXazKH2QLJfbSuE0tdBEPcmRnh7r7YA+hzbtJTKdt0i9Gwzk7cW4CETkgTR8+k80k8iHbSHKQn93n17WiVB1oQjKYy6vfgSSsgcDrmKaAV9hFWkqBr/Dd4cQOG4ulVoC5y7fiDR2p8UA4Wv0ELODYNpTLilpijTG49bVOUuYV66P5hfFftLjyxJoIcnI783yzkAZiSz95RMuDXejJHE1WS3t2bDOPsaDpd1z7wvbrGN1cUJOX2IFUDexXC5bZ5yevUY3T+7pASf0r3BIWBosxblxkvnh4oMMGXIFEpfUuiQSr84yshwiAA18Go6BH+BhDiNcVmqQ5tAxNNNwLgyRK1Pz5SQNMgvobvY+QcYezwM21JnU8pAdCqspl+98aWVqNaQXKtLQhZZPJY0Kgan+3YxfGHaUZ8QaWXWkME=
conda_forge_output_validation: true
