travis:
  secure:
    BINSTAR_TOKEN: n/dZh5ZeXlOvI4HIG07D9hEWXtsOWm+nik2SCImpuVeCvX44roxePkOyafDgVM8D/t4tKchT2Uxs7dXaY7NfLZIEyt/ZMczPgZ1ZB8H/R1xMBByr1j5efD7ETv7PGxmnoOXRuN5jX4TfqqunlsEQWEbk6O/fUNYJLB05q9nrgWp6ucwBorACIL33fXT4ziR7a2o9G02dqeiviOWQRewYiWGbmjf9q0CQ7rFH2IeMrX8IfXS1jHTUWKQ2gJvBMlSIiCj5VhXo1uLJuPFs20uB8wXHhTbjuh/cIzc1uxUOT9rQJ//+UxM4vrRb26S6IBFYI3Rl6vOLwshHhdFcHJkWSO9+ikR/OfeITG32/KPYPBbSCyUlpwzeL7aetabJkvf1yPDdqGi7H6VprElkJ5aK4NdlrG49DMoMYVFq2Dj3ohMwLoGnOtDiYgykVZmxF745QL1jXF5tQw3zYXD+cx/oz9CDBP0+Pa+T+u2VWx45i+xnLf/YViX5Yegg+GxAnDG1Y6FKzd8JxJFjNb7zEku6n6wHONLG3aFn5blN2gr23LoNLXR0xiJFE4ea2/vsJJPlmVyZw8WcruNbxgRbGR/wCvobRXxX8aOh+H9+vaQhMc9pUrHDwwg3/SjgKTkZmTrQzy/LdptdTeqxWtkL7EI8jCs9S8K0uRi4w2paavILhkM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
